<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LARGA.Shared.Models\LARGA.Shared.Models.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Plugin.Firebase" Version="4.1.0" />
	</ItemGroup>

</Project>
